### ISSUE TITLE
Performance Opportunity in SimpleConsensusClustering._fit_predict_coincidence

### ISSUE THREAD

**Issue by bryansmith-db** [bejar/kemlglearn#4]
I was using kemlglearn to perform concensus clustering and was running into some performance issues as I increased the number of base clusters and cluster count.  I examined the code in github and believe the issue is related to this block of code:

for l in baseclust:  
  for i in range(X.shape[0]):
    coin_matrix[i, i] += 1  
    for j in range(i+1, X.shape[0]):
      if l[i] == l[j]:
        coin_matrix[i, j] += 1
        coin_matrix[j, i] += 1  

In a test, I was able to recreate coin_matrix with a big performance boost by re-implementing this block as follows:

  c = base_model.labels_
  m = (c[None,:] == c[:,None]).astype(int)
  coin_matrix = np.add(coin_matrix, m)

(You could implement this a little more elegantly with some changes to the code block that proceeds it but I figure that could come later.)

In a test run with 1000 base clusters, performance dropped from 1.3 hrs to less than 1 minute.  The values for coin_matrix were found to be identical (when the same base clusters were used to construct the matrix).  I hope this is helpful.

**Comment by bejar** [comment]
thanks a lot I will update the code with your suggestion

**Comment by bejar** [comment]
Just updated the code
